### ISSUE TITLE
How did you recover the models from the HWF file?

### ISSUE THREAD

**Issue by nikitalita** [wyskoj/midijam-hacked#1]
I was briefly attempting to do what you did here, but I wasn't able to get the models out of the HWF file; It appears to be a milkshape 3d file, but opening the HWF file in it results in many errors being thrown about invalid vertices. How were you able to do this?

**Comment by wyskoj** [comment]
The HWF file itself is not a Milkshape file, but rather a collection of Milkshape files and bitmaps. But it's not anything common (it's possible that it's a proprietary format by Scott Haag). I wrote a custom scraper to extract them from the file. 

To be exact, the format of the HWF file is a binary stream of all .ms3d files, then all .bmp files, then, for each file, 260 bytes of garbage data (but the first _n_ bytes of this are the name of the file, where _n_ is the length of the filename), then a 32-bit integer LSB of the file size.

The rest of the bytes in each "garbage data" might not be garbage data per se, but I couldn't make any sense of it.

You can see my implementation of a parser [here](https://github.com/wyskoj/HWFEditor/blob/89af2adf0e2049ce38ce5c44e38940b85a38ce3f/src/main/java/org/wysko/hwfeditor/HWFEditor.java#L126).
